"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
import os
import dj_database_url

from dotenv import load_dotenv


# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables
load_dotenv(BASE_DIR / '.env')


# Security

SECRET_KEY = os.getenv(
    'SECRET_KEY'
)


DEBUG = os.getenv(
    'DEBUG',
    'False'
).lower() == 'true'


# Allowed Hosts

ALLOWED_HOSTS = os.getenv(
    'ALLOWED_HOSTS',
    '127.0.0.1,localhost'
).split(',')


# Application definition

INSTALLED_APPS = [

    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',


    # Cloudinary
    'cloudinary',
    'cloudinary_storage',


    # Django Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',


    # Our Apps
    'core',
    'accounts',
    'hotels',
    'bookings',
    'payments',

]


# Middleware

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',


    # WhiteNoise
    'whitenoise.middleware.WhiteNoiseMiddleware',


    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',


    # Django Allauth
    'allauth.account.middleware.AccountMiddleware',


    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


ROOT_URLCONF = 'config.urls'


# Templates

TEMPLATES = [

    {
        'BACKEND': (
            'django.template.backends.django.'
            'DjangoTemplates'
        ),

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


WSGI_APPLICATION = 'config.wsgi.application'


# Database

# Database

DATABASES = {

    'default': dj_database_url.config(
        default=(
            f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
        ),
        conn_max_age=600,
        conn_health_checks=True,
    )

}


# Password validation

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },

]


# Internationalization

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'UTC'


USE_I18N = True


USE_TZ = True


# Authentication

AUTHENTICATION_BACKENDS = [

    # Django admin authentication
    'django.contrib.auth.backends.ModelBackend',


    # Django Allauth authentication
    'allauth.account.auth_backends.AuthenticationBackend',

]


LOGIN_REDIRECT_URL = 'home'


LOGOUT_REDIRECT_URL = 'home'


# Django Sites

SITE_ID = 1


# Static Files

STATIC_URL = '/static/'


STATIC_ROOT = BASE_DIR / 'staticfiles'


STORAGES = {

    'default': {
        'BACKEND': (
            'cloudinary_storage.storage.'
            'MediaCloudinaryStorage'
        ),
    },


    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.'
            'CompressedManifestStaticFilesStorage'
        ),
    },

}


# Cloudinary Configuration

CLOUDINARY_STORAGE = {

    'CLOUD_NAME': os.getenv(
        'CLOUDINARY_CLOUD_NAME'
    ),

    'API_KEY': os.getenv(
        'CLOUDINARY_API_KEY'
    ),

    'API_SECRET': os.getenv(
        'CLOUDINARY_API_SECRET'
    ),

}


# Default primary key field type

DEFAULT_AUTO_FIELD = (
    'django.db.models.BigAutoField'
)


# Email

MAILERS = {

    'default': {

        'BACKEND': (
            'django.core.mail.backends.console.'
            'EmailBackend'
        ),

    },

}


# Google OAuth

GOOGLE_CLIENT_ID = os.getenv(
    'GOOGLE_CLIENT_ID'
)


GOOGLE_CLIENT_SECRET = os.getenv(
    'GOOGLE_CLIENT_SECRET'
)


# Razorpay

RAZORPAY_KEY_ID = os.getenv(
    'RAZORPAY_KEY_ID'
)


RAZORPAY_KEY_SECRET = os.getenv(
    'RAZORPAY_KEY_SECRET'
)