"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
import os

from dotenv import load_dotenv


# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings

# Security
SECRET_KEY = os.getenv(
    'SECRET_KEY'
)


DEBUG = os.getenv(
    'DEBUG',
    'False'
) == 'True'


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',


    # Django Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',


    # Our Apps
    'core',
    'accounts',
    'hotels',
    'bookings',
    'payments',

]


MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',


    # Django Allauth
    'allauth.account.middleware.AccountMiddleware',


    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


ROOT_URLCONF = 'config.urls'


# Templates

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


WSGI_APPLICATION = 'config.wsgi.application'


# Database

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }

}


# Password validation

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },

]


# Internationalization

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'UTC'


USE_I18N = True


USE_TZ = True


# Authentication

AUTHENTICATION_BACKENDS = [

    # Django admin login
    'django.contrib.auth.backends.ModelBackend',


    # Django Allauth authentication
    'allauth.account.auth_backends.AuthenticationBackend',

]


LOGIN_REDIRECT_URL = 'home'


LOGOUT_REDIRECT_URL = 'home'


# Django Sites

SITE_ID = 1


# Static files

STATIC_URL = 'static/'


# Media files

MEDIA_URL = '/media/'


MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email

MAILERS = {

    'default': {

        'BACKEND': (
            'django.core.mail.backends.console.'
            'EmailBackend'
        ),

    },

}


# Google OAuth

GOOGLE_CLIENT_ID = os.getenv(
    'GOOGLE_CLIENT_ID'
)


GOOGLE_CLIENT_SECRET = os.getenv(
    'GOOGLE_CLIENT_SECRET'
)


# Razorpay

RAZORPAY_KEY_ID = os.getenv(
    'RAZORPAY_KEY_ID'
)


RAZORPAY_KEY_SECRET = os.getenv(
    'RAZORPAY_KEY_SECRET'
)